export const tracks = [
    {
      id: 1,
      title: "Messing Around",
      artist: "Trent",
      album: "FL Studio Box",
      artwork: "/assets/album/fl_studio_box.png?height=40&width=40",
      duration: 150,
      dateAdded: "9 hours ago",
      url: "/assets/tracks/1.wav",
    },
    {
      id: 2,
      title: "Lofi, Good Try",
      artist: "Trent",
      album: "FL Studio Box",
      artwork: "/assets/album/fl_studio_box.png?height=40&width=40",
      duration: 163,
      dateAdded: "3 days ago",
      url: "/assets/tracks/lofi_good_start.wav",
    },
    {
      id: 3,
      title: "Looper Alone Freestyle",
      artist: "Trent",
      album: "Logic Box",
      artwork: "/assets/album/logic_box.png?height=40&width=40",
      duration: 131,
      dateAdded: "3 days ago",
      url: "/assets/tracks/looper_alone_mobile.mp3",
    },
    {
      id: 4,
      title: "Move Around",
      artist: "Trent",
      album: "Ableton Live Box",
      artwork: "/assets/album/ableton_live_box.png?height=40&width=40",
      duration: 81,
      dateAdded: "4 days ago",
      url: "/assets/tracks/try_it.wav",
    },
    {
      id: 5,
      title: "Do or Die",
      artist: "Trent",
      album: "Loop Station Box",
      artwork: "/assets/album/loop_station_box.png?height=40&width=40",
      duration: 274,
      dateAdded: "4 days ago",
      url: "/assets/tracks/do_or_die.wav",
    },

  ];
  