export const tracks = [
    {
      id: 1,
      title: "Unscripted Melody",
      artist: "Trent",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 225,
      dateAdded: "9 hours ago",
      url: "/path-to-audio-1.mp3",
    },
    {
      id: 2,
      title: "Spontaneous Rhythm",
      artist: "Trent ft. The Band",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 198,
      dateAdded: "3 days ago",
      url: "/path-to-audio-2.mp3",
    },
    {
      id: 3,
      title: "Freestyle Flow",
      artist: "Trent",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 184,
      dateAdded: "3 days ago",
      url: "/path-to-audio-3.mp3",
    },
    {
      id: 4,
      title: "Audience Collaboration",
      artist: "Trent & The Crowd",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 246,
      dateAdded: "4 days ago",
      url: "/path-to-audio-4.mp3",
    },
    {
      id: 5,
      title: "Musical Journey",
      artist: "Trent",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 215,
      dateAdded: "5 days ago",
      url: "/path-to-audio-5.mp3",
    },
  ];