export const tracks = [
  {
    id: 1,
    title: "Messing Around",
    artist: "Trent",
    album: "FL Studio Box",
    artwork: "/assets/album/fl_studio_box.png?height=40&width=40",
    duration: 150,
    dateAdded: new Date("2024-10-24T00:00:00"),
    url: "/assets/tracks/1.mp3",
  },
  {
    id: 2,
    title: "Lofi, Good Try",
    artist: "Trent",
    album: "FL Studio Box",
    artwork: "/assets/album/fl_studio_box.png?height=40&width=40",
    duration: 163,
    dateAdded: new Date("2024-10-27T00:00:00"),
    url: "/assets/tracks/lofi_good_start.mp3",
  },
  {
    id: 3,
    title: "Looper Alone Freestyle",
    artist: "Trent",
    album: "Logic Box",
    artwork: "/assets/album/logic_box.png?height=40&width=40",
    duration: 131,
    dateAdded: new Date("2023-10-11T00:00:00"),
    url: "/assets/tracks/looper_alone_mobile.mp3",
  },
  {
    id: 4,
    title: "Move Around",
    artist: "Trent",
    album: "Ableton Live Box",
    artwork: "/assets/album/ableton_live_box.png?height=40&width=40",
    duration: 81,
    dateAdded: new Date("2024-11-10T00:00:00"),
    url: "/assets/tracks/try_it.mp3",
  },
  {
    id: 5,
    title: "Do or Die",
    artist: "Trent",
    album: "Loop Station Box",
    artwork: "/assets/album/loop_station_box.png?height=40&width=40",
    duration: 274,
    dateAdded: new Date("2024-11-15T10:00:00"),
    url: "/assets/tracks/do_or_die.mp3",
  },
];
