export const tracks = [
    {
      id: 1,
      title: "Messing Around",
      artist: "Trent",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 225,
      dateAdded: "9 hours ago",
      url: "/assets/tracks/1.wav",
    },
    {
      id: 2,
      title: "Spontaneous Rhythm",
      artist: "Trent ft. The Band",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 198,
      dateAdded: "3 days ago",
      url: "/path-to-audio-2.mp3",
    },
    {
      id: 3,
      title: "Freestyle Flow",
      artist: "Trent",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 184,
      dateAdded: "3 days ago",
      url: "/path-to-audio-3.mp3",
    },
    {
      id: 4,
      title: "Audience Collaboration",
      artist: "Trent & The Crowd",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 246,
      dateAdded: "4 days ago",
      url: "/path-to-audio-4.mp3",
    },
    {
      id: 5,
      title: "Musical Journey",
      artist: "Trent",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 215,
      dateAdded: "5 days ago",
      url: "/path-to-audio-5.mp3",
    },
    {
      id: 6,
      title: "Echoes of Silence",
      artist: "Trent",
      album: "Deep Thoughts",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 230,
      dateAdded: "6 days ago",
      url: "/path-to-audio-6.mp3",
    },
    {
      id: 7,
      title: "Midnight Groove",
      artist: "Trent",
      album: "Night Vibes",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 210,
      dateAdded: "1 week ago",
      url: "/path-to-audio-7.mp3",
    },
    {
      id: 8,
      title: "Harmony in Chaos",
      artist: "Trent & The Band",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 255,
      dateAdded: "1 week ago",
      url: "/path-to-audio-8.mp3",
    },
    {
      id: 9,
      title: "Wandering Mind",
      artist: "Trent",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 195,
      dateAdded: "2 weeks ago",
      url: "/path-to-audio-9.mp3",
    },
    {
      id: 10,
      title: "Soulful Expressions",
      artist: "Trent",
      album: "Deep Thoughts",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 240,
      dateAdded: "2 weeks ago",
      url: "/path-to-audio-10.mp3",
    },
    {
      id: 11,
      title: "Ambient Waves",
      artist: "Trent",
      album: "Chill Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 220,
      dateAdded: "3 weeks ago",
      url: "/path-to-audio-11.mp3",
    },
    {
      id: 12,
      title: "Electric Dreams",
      artist: "Trent",
      album: "Night Vibes",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 205,
      dateAdded: "3 weeks ago",
      url: "/path-to-audio-12.mp3",
    },
    {
      id: 13,
      title: "Rhythmic Pulse",
      artist: "Trent ft. DJ Mix",
      album: "Club Nights",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 235,
      dateAdded: "1 month ago",
      url: "/path-to-audio-13.mp3",
    },
    {
      id: 14,
      title: "Sunrise Melody",
      artist: "Trent",
      album: "Morning Tunes",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 215,
      dateAdded: "1 month ago",
      url: "/path-to-audio-14.mp3",
    },
    {
      id: 15,
      title: "Whispers in the Wind",
      artist: "Trent",
      album: "Deep Thoughts",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 225,
      dateAdded: "1 month ago",
      url: "/path-to-audio-15.mp3",
    },
    {
      id: 16,
      title: "Dance of Shadows",
      artist: "Trent & The Band",
      album: "Live Sessions",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 250,
      dateAdded: "2 months ago",
      url: "/path-to-audio-16.mp3",
    },
    {
      id: 17,
      title: "Echo Chamber",
      artist: "Trent",
      album: "Improv Night",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 205,
      dateAdded: "2 months ago",
      url: "/path-to-audio-17.mp3",
    },
    {
      id: 18,
      title: "Silent Reflections",
      artist: "Trent",
      album: "Deep Thoughts",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 240,
      dateAdded: "3 months ago",
      url: "/path-to-audio-18.mp3",
    },
    {
      id: 19,
      title: "City Lights",
      artist: "Trent",
      album: "Night Vibes",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 200,
      dateAdded: "3 months ago",
      url: "/path-to-audio-19.mp3",
    },
    {
      id: 20,
      title: "Endless Horizons",
      artist: "Trent",
      album: "Journey",
      artwork: "/placeholder.svg?height=40&width=40",
      duration: 260,
      dateAdded: "4 months ago",
      url: "/path-to-audio-20.mp3",
    },
  ];
  